## get the datasets


In [68]:
import pandas as pd

In [69]:
import numpy as np

In [70]:
df=pd.read_csv("train.csv")

In [71]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [72]:
X=df["Age"]

In [73]:
X

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [74]:
y=df["Survived"]

In [75]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [76]:
X.shape

(891,)

In [77]:
y.shape

(891,)

In [78]:
df["PassengerId"]

0        1
1        2
2        3
3        4
4        5
      ... 
886    887
887    888
888    889
889    890
890    891
Name: PassengerId, Length: 891, dtype: int64

In [79]:
X.isna().sum() #isna is used to get number of missing values

177

In [80]:
X=X.fillna(method="ffill") # fillna is used to fillin missing values(ffill=forward fill and bfill = backward fill)

In [81]:
X

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888    19.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [82]:
X.isna().sum()

0

In [83]:
X.ndim

1

In [84]:
type(X) #type is used to tell the type of object

pandas.core.series.Series

In [85]:
X.values # .values is used to convert it to a numpy array

array([22.  , 38.  , 26.  , 35.  , 35.  , 35.  , 54.  ,  2.  , 27.  ,
       14.  ,  4.  , 58.  , 20.  , 39.  , 14.  , 55.  ,  2.  ,  2.  ,
       31.  , 31.  , 35.  , 34.  , 15.  , 28.  ,  8.  , 38.  , 38.  ,
       19.  , 19.  , 19.  , 40.  , 40.  , 40.  , 66.  , 28.  , 42.  ,
       42.  , 21.  , 18.  , 14.  , 40.  , 27.  , 27.  ,  3.  , 19.  ,
       19.  , 19.  , 19.  , 19.  , 18.  ,  7.  , 21.  , 49.  , 29.  ,
       65.  , 65.  , 21.  , 28.5 ,  5.  , 11.  , 22.  , 38.  , 45.  ,
        4.  ,  4.  ,  4.  , 29.  , 19.  , 17.  , 26.  , 32.  , 16.  ,
       21.  , 26.  , 32.  , 25.  , 25.  , 25.  ,  0.83, 30.  , 22.  ,
       29.  , 29.  , 28.  , 17.  , 33.  , 16.  , 16.  , 23.  , 24.  ,
       29.  , 20.  , 46.  , 26.  , 59.  , 59.  , 71.  , 23.  , 34.  ,
       34.  , 28.  , 28.  , 21.  , 33.  , 37.  , 28.  , 21.  , 21.  ,
       38.  , 38.  , 47.  , 14.5 , 22.  , 20.  , 17.  , 21.  , 70.5 ,
       29.  , 24.  ,  2.  , 21.  , 21.  , 32.5 , 32.5 , 54.  , 12.  ,
       12.  , 24.  ,

In [86]:
X=X.values

In [87]:
X

array([22.  , 38.  , 26.  , 35.  , 35.  , 35.  , 54.  ,  2.  , 27.  ,
       14.  ,  4.  , 58.  , 20.  , 39.  , 14.  , 55.  ,  2.  ,  2.  ,
       31.  , 31.  , 35.  , 34.  , 15.  , 28.  ,  8.  , 38.  , 38.  ,
       19.  , 19.  , 19.  , 40.  , 40.  , 40.  , 66.  , 28.  , 42.  ,
       42.  , 21.  , 18.  , 14.  , 40.  , 27.  , 27.  ,  3.  , 19.  ,
       19.  , 19.  , 19.  , 19.  , 18.  ,  7.  , 21.  , 49.  , 29.  ,
       65.  , 65.  , 21.  , 28.5 ,  5.  , 11.  , 22.  , 38.  , 45.  ,
        4.  ,  4.  ,  4.  , 29.  , 19.  , 17.  , 26.  , 32.  , 16.  ,
       21.  , 26.  , 32.  , 25.  , 25.  , 25.  ,  0.83, 30.  , 22.  ,
       29.  , 29.  , 28.  , 17.  , 33.  , 16.  , 16.  , 23.  , 24.  ,
       29.  , 20.  , 46.  , 26.  , 59.  , 59.  , 71.  , 23.  , 34.  ,
       34.  , 28.  , 28.  , 21.  , 33.  , 37.  , 28.  , 21.  , 21.  ,
       38.  , 38.  , 47.  , 14.5 , 22.  , 20.  , 17.  , 21.  , 70.5 ,
       29.  , 24.  ,  2.  , 21.  , 21.  , 32.5 , 32.5 , 54.  , 12.  ,
       12.  , 24.  ,

In [88]:
type(X)

numpy.ndarray

In [89]:
X=X.reshape(-1,1)

In [90]:
X

array([[22.  ],
       [38.  ],
       [26.  ],
       [35.  ],
       [35.  ],
       [35.  ],
       [54.  ],
       [ 2.  ],
       [27.  ],
       [14.  ],
       [ 4.  ],
       [58.  ],
       [20.  ],
       [39.  ],
       [14.  ],
       [55.  ],
       [ 2.  ],
       [ 2.  ],
       [31.  ],
       [31.  ],
       [35.  ],
       [34.  ],
       [15.  ],
       [28.  ],
       [ 8.  ],
       [38.  ],
       [38.  ],
       [19.  ],
       [19.  ],
       [19.  ],
       [40.  ],
       [40.  ],
       [40.  ],
       [66.  ],
       [28.  ],
       [42.  ],
       [42.  ],
       [21.  ],
       [18.  ],
       [14.  ],
       [40.  ],
       [27.  ],
       [27.  ],
       [ 3.  ],
       [19.  ],
       [19.  ],
       [19.  ],
       [19.  ],
       [19.  ],
       [18.  ],
       [ 7.  ],
       [21.  ],
       [49.  ],
       [29.  ],
       [65.  ],
       [65.  ],
       [21.  ],
       [28.5 ],
       [ 5.  ],
       [11.  ],
       [22.  ],
       [38.  ],
       [

In [91]:
X.shape

(891, 1)

In [92]:
y.shape

(891,)

In [93]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

## MODELLING

In [94]:
from sklearn.neighbors import KNeighborsClassifier

In [95]:
knn=KNeighborsClassifier()

In [96]:
knn

KNeighborsClassifier()

In [97]:
knn.fit(X,y)

KNeighborsClassifier()

In [98]:
knn.predict([[50]])

array([0], dtype=int64)

In [99]:
knn.fit(X,y)

KNeighborsClassifier()

In [100]:
knn.predict([[12]])

array([0], dtype=int64)

In [66]:
knn.score(X,y)

0.6083052749719416

In [101]:
type(y)

pandas.core.series.Series

In [103]:
y.value_counts()

0    549
1    342
Name: Survived, dtype: int64

In [104]:
342/891

0.3838383838383838

In [105]:
1-342/891

0.6161616161616161

## MODIFIED THE FEATURE MATRIX

In [106]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [107]:
X=df["Age","Fare"]

KeyError: ('Age', 'Fare')

In [108]:
X=df.loc[:,["Age","Fare"]]

In [111]:
X.head()

Age     Fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [112]:
X.isna().sum()

Age     177
Fare      0
dtype: int64

In [113]:
X.fillna(method="bfill",inplace=True)

In [114]:
X.isna().sum()

Age     0
Fare    0
dtype: int64

In [115]:
X.shape

(891, 2)

In [116]:
X.ndim

2

## KNN

In [117]:
from sklearn.neighbors import KNeighborsClassifier
knn1=KNeighborsClassifier()
knn1.fit(X,y)

KNeighborsClassifier()

## Accuracy of the model(classification metric)

In [118]:
knn1.score(X,y)

0.7620650953984287

In [119]:
y_pred=knn1.predict(X)

In [120]:
y_pred

array([0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1,

In [121]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [122]:
y==y_pred


0       True
1      False
2      False
3       True
4       True
       ...  
886    False
887     True
888     True
889     True
890     True
Name: Survived, Length: 891, dtype: bool

In [123]:
(y==y_pred).sum()

679

In [124]:
(~(y==y_pred)).sum()

212

In [125]:
891-(y==y_pred).sum()

212

In [126]:
679/891

0.7620650953984287

## Logistic model

In [127]:
from sklearn.linear_model import LogisticRegression
log_model=LogisticRegression()

In [128]:
log_model

LogisticRegression()

In [129]:
log_model.fit(X,y)

LogisticRegression()

In [130]:
y_pred_log=log_model.predict(X)

In [131]:
y_pred_log

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,

In [134]:
(y==y_pred_log).sum()

589

In [135]:
590/891

0.6621773288439955

In [136]:
log_model.score(X,y)

0.6610549943883277