## Splitting and joining of arrays Indexing, slicing and Fancy Indexing

In [1]:
import numpy as np

In [49]:
x=np.linspace(10,20,10)

In [50]:
x

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [3]:
a=[[2,4,5],[5,6,7]]

In [4]:
a

[[2, 4, 5], [5, 6, 7]]

In [5]:
len(a)

2

In [6]:
a[0]

[2, 4, 5]

In [7]:
a[1]

[5, 6, 7]

In [8]:
a[-2]

[2, 4, 5]

In [9]:
a[0][1]

4

In [10]:
a[1][1]

6

In [11]:
a1=np.array(a)

In [12]:
a1

array([[2, 4, 5],
       [5, 6, 7]])

In [13]:
a1[0]

array([2, 4, 5])

In [14]:
a1[1]

array([5, 6, 7])

In [15]:
a1[0]

array([2, 4, 5])

In [16]:
a1[1][1]

6

In [17]:
a1[0][2]

5

In [18]:
a1[1,2]

7

In [51]:
x

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [52]:
x[:2]

array([10.        , 11.11111111])

In [53]:
x[:5:2]

array([10.        , 12.22222222, 14.44444444])

In [54]:
x[0:3]

array([10.        , 11.11111111, 12.22222222])

In [55]:
x[3:6]

array([13.33333333, 14.44444444, 15.55555556])

In [56]:
a1

array([[2, 4, 5],
       [5, 6, 7]])

In [31]:
a1[:,2]

array([5, 7])

In [32]:
a1[:,1:3]

array([[4, 5],
       [6, 7]])

In [33]:
a1[:,0:2]

array([[2, 4],
       [5, 6]])

In [34]:
a1[1:,]

array([[5, 6, 7]])

In [36]:
y=np.random.randint(2,20,(4,5))

In [37]:
y

array([[11,  6, 12, 16,  6],
       [10,  7, 12,  9, 14],
       [ 3, 12, 13, 12,  4],
       [10, 12, 10, 18, 10]])

In [38]:
y[:2]

array([[11,  6, 12, 16,  6],
       [10,  7, 12,  9, 14]])

In [39]:
y[:2,:2]

array([[11,  6],
       [10,  7]])

In [40]:
y[2:4,1:3]

array([[12, 13],
       [12, 10]])

In [41]:
y[2,2]

13

In [44]:
y[3,4]

10

In [45]:
y[0,0]

11

# Fancy Indexing

In [57]:
x

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [58]:
x[::2]

array([10.        , 12.22222222, 14.44444444, 16.66666667, 18.88888889])

In [59]:
x[[0,2,6]]

array([10.        , 12.22222222, 16.66666667])

In [60]:
y

array([[11,  6, 12, 16,  6],
       [10,  7, 12,  9, 14],
       [ 3, 12, 13, 12,  4],
       [10, 12, 10, 18, 10]])

In [62]:
y[[0,1,2],[0,1,2]]

array([11,  7, 13])

In [63]:
y[[0,2,3],[0,3,3]]

array([11, 12, 18])

## Loading Datasets

In [1]:
file=open("grad_survey.csv","r")
content=file.read
file.close()
print(content)

<built-in method read of _io.TextIOWrapper object at 0x0598C028>


In [2]:
file=open("grad_survey.csv")
for row in file.readlines()[:10]:

SyntaxError: unexpected EOF while parsing (<ipython-input-2-59bb83584b61>, line 2)